dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      # 缩写为chainlink 并在合约文件的import中使用. 用于import github上的代码
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
dotenv: .env #环境变量文件
networks: #用于存储网络的额外信息/变量. 
  mainnet-fork:
    # 网络的eth/usd price feed地址
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    # 在该网络上部署合约是否要提交到etherscan进行合约审查
    verify: False
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True
  ganache-local:
    verify: False 
  development:
    verify: False
wallets:  #钱包 
  from_key: ${PRIVATE_KEY}